---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nwapp-cm
  labels:
    app: northwind
data:
  DB_USER: root
  DB_HOST: nwdb-cluster-mysql.nw.svc.cluster.local #FQDN, usable across NS in same cluster
  # DB_HOST: http://nwdb-svc:8080 # Usable if in same NS
---
# Deployment: App servers
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nwapp-deploy
  labels:
    app: northwind
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nwapp-pod
  template:
    metadata:
      name: nwapp-pod
      labels:
        app: nwapp-pod
    spec:
      containers:
      - name: nwapp-container
        image: chukmunnlee/my-nwapp:v1
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            cpu: 200m
            memory: 32Mi
          limits:
            memory: 64Mi
        envFrom:
        - configMapRef:
            name: nwapp-cm
        env:
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: ROOT_PASSWORD
        - name: INSTANCE_IP_ADDRESS
          valueFrom: 
            fieldRef: 
              fieldPath: status.podIP
        ports:
        - name: nwapp-port
          containerPort: 3000

---
apiVersion: v1
kind: Service
metadata:
  name: nwapp-svc
  labels:
    app: northwind
spec:
  type: ClusterIP
  selector:
    app: nwapp-pod
  ports:
  - name: nwapp-svc-port
    port: 3000
    targetPort: nwapp-port

---
# Rules for routing incoming requests
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: nwapp-ing
  labels:
    app: northwind
spec:
  rules:
  - host: nw.167.172.5.47.nip.io #nginx-ingress location
    http:
      paths:
      - path: /
        backend: # where to send services that match the path
          serviceName: nwapp-svc
          servicePort: nwapp-svc-port
---
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: nwapp-hpa
  labels:
    app: northwind
spec:
  minReplicas: 1
  maxReplicas: 4
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: nwapp-deploy
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 15 # Normally set to 80 
  - type: Resource
    resource:
      name: memory
      target: 
        type: Utilization
        averageUtilization: 50