---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nwdb-pvc
  labels:
    app: northwind
  annotations:
    # Define the provisioner
    volume.beta.kubernetes.io/storage-provisioner: dobs.csi.digitalocean.com 

spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: do-block-storage # from kubectl get sc
  resources:
    requests:
      storage: 1Gi