---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wp-pvc
  labels:
    app: wordpress

spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: do-block-storage # from kubectl get sc
  resources:
    requests:
      storage: 1Gi
  volumeMode: Filesystem